### ISSUE TITLE
复现代码

### ISSUE THREAD

**Issue by huanghonggit** [ZaoZhe6666/ReadTheDocs#1]
您好，您能不能提供案例一：用FGSM做白盒测试的代码； 想学习下您的代码

**Comment by ZaoZhe6666** [comment]
不知道链接能看到吗，您看一下，这是ReadTheDocs那个文档对应的代码[《DIG/AISafety》](https://github.com/DIG-Beihang/AISafety)

**Comment by huanghonggit** [comment]
非常感谢您的分享~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZaoZhe6666/ReadTheDocs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月3日(星期四) 晚上6:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZaoZhe6666/ReadTheDocs] 复现代码 (#1)





 
不知道链接能看到吗，您看一下，这是ReadTheDocs那个文档对应的代码《DIG/AISafety》
